"""MuseHub route package.

Auto-discovers and registers all sub-routers. Registered in ``musehub.main`` as:

    app.include_router(musehub.router, prefix="/api/v1", tags=["musehub"])

**Agent instruction — DO NOT EDIT THIS FILE.**
To add a new endpoint group, create a new module in this package that
exposes a ``router = APIRouter(...)`` attribute. It will be picked up
automatically on the next server start. No changes to this file are needed.

Registration order:
- ``analysis.harmony_router`` is registered before ``analysis.router`` so
  the specific ``/analysis/{ref}/harmony`` path takes priority over the
  generic ``/{dimension}`` catch-all declared in ``analysis.router``.
- All other modules are registered alphabetically.
- ``repos`` is always last because it declares the ``/{owner}/{repo_slug}``
  wildcard route, which must not shadow any fixed-path routes.

Auth policy:
- Public repo GET endpoints use ``optional_token`` — unauthenticated
  access is allowed for public repos; private repos return 401.
- Write endpoints (POST/PUT/DELETE) always use ``require_valid_token``
  declared on the individual route handler.
"""

import importlib
import pkgutil
from pathlib import Path

from fastapi import APIRouter

from musehub.api.routes.musehub import analysis

router = APIRouter(prefix="")

_PACKAGE = "musehub.api.routes.musehub"
_HERE = [str(Path(__file__).parent)]

# harmony_router first: specific /analysis/{ref}/harmony must beat the
# generic /{dimension} catch-all declared in analysis.router.
router.include_router(analysis.harmony_router, tags=["Analysis"])

# Modules registered directly in main.py (with their own prefix/placement)
# must be excluded here to prevent double-registration and duplicate operationIds.
_DIRECT_REGISTERED = {
    "discover",        # registered in main.py at /api/v1 (has /musehub/discover hardcoded)
    "sitemap",         # registered in main.py at root (sitemap.xml, robots.txt)
    "ui_new_repo",     # registered in main.py at root (has /musehub/ui hardcoded prefix)
    "ui",              # registered in main.py at root (router + fixed_router)
    "ui_blame",        # registered in main.py at root
    "ui_collaborators",# registered in main.py at root
    "ui_emotion_diff", # registered in main.py at root
    "ui_forks",        # registered in main.py at root
    "ui_labels",       # registered in main.py at root
    "ui_milestones",   # registered in main.py at root
    "ui_notifications",# registered in main.py at root
    "ui_settings",     # registered in main.py at root
    "ui_similarity",   # registered in main.py at root
    "ui_stash",        # registered in main.py at root
    "ui_topics",       # registered in main.py at root
    "ui_mcp_elicitation", # registered in main.py at root (MCP elicitation UI pages)
    "ui_user_profile", # registered in main.py at root
    "users",           # registered in main.py at /api/v1/musehub (same path as auto-discovery)
    "oembed",          # registered in main.py at root
    "raw",             # registered in main.py at /api/v1
}

# Load every sibling module that exposes a `router` attribute, alphabetically.
# repos goes last to avoid shadowing fixed-path routes with its wildcard.
for _mod_info in sorted(
    pkgutil.iter_modules(_HERE),
    key=lambda m: (m.name == "repos", m.name),
):
    if _mod_info.name in _DIRECT_REGISTERED:
        continue
    _mod = importlib.import_module(f"{_PACKAGE}.{_mod_info.name}")
    if hasattr(_mod, "router"):
        _tag = _mod_info.name.replace("_", " ").title()
        router.include_router(_mod.router, tags=[_tag])

__all__ = ["router"]
